### ISSUE TITLE
PHP8 support?

### ISSUE THREAD

**Issue by KieronWiltshire** [ge-tracker/laravel-vapor-trusted-proxies#1]
When can we expect php8 and laravel 8 support for this package?

**Comment by gtjamesa** [comment]
Hey,

I've just tagged release [v1.0.3](https://packagist.org/packages/ge-tracker/laravel-vapor-trusted-proxies#v1.0.3). I've added PHP 8 and the [tests are passing](https://github.com/ge-tracker/laravel-vapor-trusted-proxies/actions/runs/689268440). Let me know if you have any problems.
